Hilt Boilerplate
DDD-Community/appcha-android pull request #14
Opened 2021-09-17 17:44 UTC by peterchoee

## 개요
- DI 구현을 위해 Hilt를 사용해 환경을 구축합니다.

## 작업사항
- 작업된 코드에 대해서 Hilt 적용
- 작업범위: Activity, ViewModel, UseCase, Repository, DataSource

## 기타
- kotlin-jvm 에서는 안드로이드 종속성을 가지는 Hilt 모듈 설정을 할 수 없어서 해당 모듈에 대해서는 app 모듈에서 진행했습니다.

2021-09-18 02:27 UTC, laco-dev requested changes
모듈과 Impl에 전부 internal 붙여주세요. 인터페이스로 의존성을 주고받기 때문에 구현체를 외부에서 알 필요가 없습니다.

`hilt-android` 모듈로 인해 app에서 주입받게 된 거라면
`hilt-core`를 사용하면 됩니다.
https://mvnrepository.com/artifact/com.google.dagger/hilt-core/2.38.1

리뷰 반영되면 다시 보겠습니다

2021-09-18 02:27 UTC, laco-dev commented on modules/local/src/main/java/com/editor/appcha/local/di/Module.kt
> +abstract class Module {
`DataSourceModule`로 이름 변경 해 주세요

2021-09-18 05:02 UTC, peterchoee commented on modules/local/src/main/java/com/editor/appcha/local/di/Module.kt
> +abstract class Module {
오! hilt-core 존재는 몰랐네요. 각 모듈에서 주입하도록 수정할게요~
internal로 했을때는 @Binds 주입은 안될 것 같은데 괜찮을까요~?

2021-09-18 05:27 UTC, laco-dev commented on modules/local/src/main/java/com/editor/appcha/local/di/Module.kt
> +abstract class Module {
해당 모듈에서 주입 하는 코드를 작성 해 주시면 됩니다.
data면 DataModule에서 해주시면 되어요

2021-09-18 05:36 UTC, peterchoee commented on modules/local/src/main/java/com/editor/appcha/local/di/Module.kt
> +abstract class Module {
넵넵! 말씀주신 내용은 이해하고 있어요 ㅎ
주입 방식에 있어서 @Provides 주입을 말고 @Binds 주입을 하려했는데 internal 접근제한자로 뒀을때는 @Binds 함수에 생성자로 넣어줄 수 없어서 거기에 대해서 여쭤봤어요 ㅎㅎ

2021-09-28 14:36 UTC, peterchoee reviewed
헐.... 컴파일러.... 생각지도 못했네요 ㅠㅠ 감사합니다 🙏

2021-09-29 12:20 UTC, laco-dev approved these changes
LGTM 🐈 👍 🐕

2021-09-29 12:31 UTC, peterchoee commented
> LGTM 🐈 👍 🐕

영직님 덕분에 세이프!!

2021-09-29 12:31 UTC, merged