카카오 로그인 관련 화면 개발
DDD-Community/appcha-android pull request #22
Opened 2021-10-20 14:46 UTC by peterchoee

**진행사항**
- 공통
  - 카카오 로그인 라이브러리 추가
  - 카카오 API Key를 config.properties에 작성하고 필요한 모듈에서 로드
- 스플래쉬
  - 자동로그인 스펙이 정해지지 않아 ViewModel 에서 Random Boolean 값에 따라 로그인 혹은 메인 화면으로 이동하도록 수정
- 로그인
  - 로그인 버튼 클릭 시 카카오 로그인 진행
  - 카카오 계정 정보 및 UseCase, Repository는 서버 스펙이 정해지면 이어 개발 진행

_현재 브랜치에서 논의되는 디자인 & 서버 진행에 따라 추가 개발 이어갑니다!_

2021-10-21 11:50 UTC, laco-dev requested changes
dev 리베이스 부탁합니다

2021-10-21 12:08 UTC, laco-dev requested changes

2021-10-21 12:08 UTC, laco-dev commented on buildSrc/src/main/kotlin/PropertyUtil.kt
> +}
프로퍼티 파일을 이렇게 읽어올 수가 있네요. 👍 

그런데 config.gradle이 외부로 노출되면 안되니 각자 개발환경의 gradle.properties에 넣고 바로 사용하면 될 것 같습니다.
사용은 gradle에서 project.properties로 바로 해도 될 듯 합니다

2021-10-21 12:08 UTC, laco-dev commented on modules/domain/src/main/java/com/editor/appcha/domain/model/User.kt
> +    )
Profile로 해주세요

2021-10-21 12:08 UTC, laco-dev commented on modules/domain/src/main/java/com/editor/appcha/domain/usecase/LoginUseCase.kt
> +}
정의되어 있는 UseCase 추상 클래스를 구현해서 사용 해 주세요

2021-10-21 12:08 UTC, laco-dev commented on modules/domain/src/main/java/com/editor/appcha/domain/repo/LoginRepository.kt
> +}
Flow로 반환하는 이유가 있나요?

2021-10-21 12:08 UTC, laco-dev commented on modules/ui/src/main/java/com/editor/appcha/ui/login/LoginScreen.kt
> +fun LoginActivityScreen(activity: Activity, viewModel: LoginViewModel, kakaoLoginProvider: KakaoLoginProvider) {
Composable이 Activiy나 Kakao sdk에 접근하지 않도록 해주세요
콜백을 위로 끌어올려서 액티비티에서 호출하게 해야 합니다

2021-10-21 12:08 UTC, laco-dev commented on modules/ui/src/main/java/com/editor/appcha/ui/login/LoginScreen.kt
> +        contentPadding = PaddingValues(top = 12.dp, bottom = 12.dp)
```kotlin
PaddingValues(vertical = 12.dp)
```

2021-10-21 12:08 UTC, laco-dev commented on modules/ui/src/main/java/com/editor/appcha/ui/login/LoginViewModel.kt
> +    }
이벤트를 단순 성공 실패로 작성하는건 지양 해 주세요.
어떤 이벤트인지 유추 할 수 있도록 하는게 좋습니다.

로그인에서는 StartHome이나 ShowErrorToast 등이 될 수 있겟네요.

2021-10-21 12:08 UTC, laco-dev commented on modules/domain/src/main/java/com/editor/appcha/domain/model/User.kt
> +) {
로그인 결과로 유저를 받아오지 못하면 유저가 없는 것인데 유저 데이터에 `isExists`같은 정보가 담기는게 말이 안되는 것 같습니다.

로그인 api 스펙 설계하면서 고려 해주세요
토큰이 프리퍼러스에 있는지 없는지로도 충분합니다.

2021-10-21 12:08 UTC, laco-dev commented on modules/ui/src/main/java/com/editor/appcha/ui/login/provider/KakaoLoginProvider.kt
> +    }
callback을 suspendCoroutine을 이용해 suspend 함수로 만드는 방법도 있습니당.
적절하게 사용하문

2021-10-21 12:08 UTC, laco-dev commented on modules/ui/src/main/java/com/editor/appcha/ui/splash/SplashViewModel.kt
> +import java.util.*
와일드카드 옵션 꺼주세요.

2021-10-22 19:03 UTC, peterchoee commented on modules/ui/src/main/java/com/editor/appcha/ui/splash/SplashViewModel.kt
> +import java.util.*
꼼꼼하게 봐주셔서 감사합니다 👍 
a3d0934

2021-10-22 19:05 UTC, peterchoee commented on modules/domain/src/main/java/com/editor/appcha/domain/repo/LoginRepository.kt
> +}
사실 큰... 이유는 없습니다 ㅎ
bfbb13b

2021-10-22 19:06 UTC, peterchoee commented on modules/domain/src/main/java/com/editor/appcha/domain/model/User.kt
> +    )
df37c85

2021-10-22 19:07 UTC, peterchoee commented on buildSrc/src/main/kotlin/PropertyUtil.kt
> +}
이 부분은 배포 하지 않을거라 크게 상관없을 것 같아서 우선 유지하겠습니다.

2021-10-22 19:07 UTC, peterchoee commented on modules/domain/src/main/java/com/editor/appcha/domain/usecase/LoginUseCase.kt
> +}
Flow 제거하면서 기존 UseCase 추상클래스로 변경했어요!
bfbb13b

2021-10-22 19:09 UTC, peterchoee commented on modules/ui/src/main/java/com/editor/appcha/ui/login/LoginScreen.kt
> +fun LoginActivityScreen(activity: Activity, viewModel: LoginViewModel, kakaoLoginProvider: KakaoLoginProvider) {
별도 인터페이스를 두도록 수정했습니다.
이 부분은 작성시에도 고민을 많이 하긴했는데요. Composable에서 필요한 파라미터로 ViewModel 로 한정하는걸로 생각하시는건가요~?
32cbf6d

2021-10-22 19:09 UTC, peterchoee commented on modules/ui/src/main/java/com/editor/appcha/ui/login/LoginViewModel.kt
> +    }
6f45c5d

2021-10-22 19:10 UTC, peterchoee commented on modules/domain/src/main/java/com/editor/appcha/domain/model/User.kt
> +) {
]API 관련 내용은 별도 코멘트로 작성하겠습니다 :)

2021-10-22 19:12 UTC, peterchoee commented
디테일하게 봐주셔서 감사합니다 👍 
API 관련 부분은 이중 작업이 될 수도 있을 것 같아서 남은 주말동안 지호님과 상의해서 결정할게요!
로컬에 저장하는 토큰을 서버에서 내려주는 값(jwt 등)으로 하거나 로그인을 시도했을때 어떤 값을 내려줄때 회원가입으로 이동시킬지 등 추후에 수정될 내용이 많을 것 같아서요!
우선 상의해보고 아무래도 일정상 빠르게 처리되지 못하면 앱 내(로컬)로만 처리되도록 하려합니다.

2021-10-22 23:10 UTC, laco-dev commented on buildSrc/src/main/kotlin/PropertyUtil.kt
> +}
깃헙이 공개되어있어서... 나중에 닫으실때 카카오키도 같이 날려버리시면 될 것같네요 👀

2021-10-22 23:13 UTC, laco-dev commented on modules/ui/src/main/java/com/editor/appcha/ui/login/LoginScreen.kt
> +fun LoginActivityScreen(activity: Activity, viewModel: LoginViewModel, kakaoLoginProvider: KakaoLoginProvider) {
재사용성과 확장 가능성에 따라 Composable에 들어가는 파라미터는 가장 low 레벨로 잡는게 좋습니다.
그러기 위해 Composable이 상태를 가지고 있거나 프레임워크 의존성을 가지는 것에 대해 상태 끌어올리기라는 State hositing전략을 사용할 수 있습니다.

LoginActivityScreen은 root Composable이라서 ViewModel은 알아도 괜찮습니다.
다만 Composable이 직접적으로 KakaoProvider에 접근하는 것은 테스트와 Preview 관점에서는 안된다고 생각하고 있습니다.

물론 Activity를 직접 알 필요도 없습니다.

2021-10-22 23:22 UTC, laco-dev approved these changes
빠른 진행을 위해 우선 승인하겠습니다.
다음에 작업하실때 같이 생각해봐주시면 될 것 같아요.

LGTM 🐈 👍 🐕

2021-10-22 23:22 UTC, laco-dev commented on modules/ui-compose/src/main/java/com/editor/appcha/ui/compose/login/provider/OnKakaoLoginListener.kt
> +}
Composable에서는 인터페이스를 기본적으로 불안정한 상태로 취급합니다.
그렇기 때문에 안정적이라고 판단할 수 있는 경우 명시적으로 `@Stable` 어노테이션을 인터페이스에 추가 해 주시면 됩니다.

이 부분은 Compose 조금 깊이 있는 내용이라 우선은 가볍게 넘겨주셔도 되구요

쉽게 풀어보면 이 인터페이스를 Composable의 파라미터로 받을때 매번 재구성이 일어날지 한번만 일어날지를 판단하는 기준이 됩니다.

https://developer.android.com/jetpack/compose/lifecycle#skipping

2021-10-22 23:22 UTC, laco-dev commented on modules/ui-compose/src/main/java/com/editor/appcha/ui/compose/login/LoginScreen.kt
> +fun LoginActivityScreen(viewModel: LoginViewModel, onKakaoLoginListener: OnKakaoLoginListener) {
단순히 로그인 시도에 대한 처리라 인터페이스로 만들 필요까지는 없다고 생각합니다.
`onLogin` 정도로 해서 () -> Unit 타입으로 넘겨도 좋을 듯 합니다.

함수 타입은 기본적으로 Stable 하기 때문에 인터페이스에 비해서 조금 더 유연하게 사용할 수 있습니다.

2021-10-23 09:27 UTC, merged