Properties 파일 제거 & Debug signingConfigs
DDD-Community/appcha-android pull request #26
Opened 2021-10-28 17:47 UTC by peterchoee

**작업내용**
- config.properties 파일을 제거 (gitignore 추가)
- config.properties 파일 내에 디버그 키스토어 관련 내용(filePath, password, alias)을 추가
  - _filePath는 각 로컬환경에 따라 변경해서 사용하면 될 것 같습니다._
- config.properties 파일 값을 참조할 수 있도록 DSL 수정
- gradle(app)에서 debug 시 키스토어를 설정하도록 추가
- [Notion > Android > 파일](https://www.notion.so/Android-b9a531b0b1784598b5b6c6d49863bfd4)에서 Debug Keystore 및 config.properties 다운로드

2021-10-29 01:44 UTC, laco-dev requested changes

2021-10-29 01:44 UTC, laco-dev commented on modules/app/build.gradle.kts
> +    }
debug면 비밀번호랑 다른작업 필요없지않나요
```kotlin
signingConfigs {
    getByName("debug") {
        storeFile = file("$rootDir/settings/debug.keystore")
    }
}
```
형태로 간단한게 끝내도 될 것 같아요. 굳이 공통으로 쓸 이유가 없어서 buildSrc에 넣을 필요 없을 듯 합니다.

buildType에도 아마 필요없을거에요?

2021-10-29 08:35 UTC, peterchoee commented on modules/app/build.gradle.kts
> +    }
debug 시에 비밀번호 등 작업이 필요없으면 굳이 properties에 명시해서 사용안해도 상관없을 것 같아요!
해당 부분은 비밀번호가 필수인줄 알았는데요. 
아직 명확하게 모르는 부분이 있는 것 같아서 좀 더 찾아보고 필요없으면 수정하겠습니다 👍

2021-10-30 19:33 UTC, peterchoee commented on modules/app/build.gradle.kts
> +    }
확인 감사합니다 👍 
292b952

2021-10-30 19:35 UTC, peterchoee commented
카카오 로그인 초기화 방식을 [androidx.startup](https://developer.android.com/topic/libraries/app-startup) 라이브러리로 변경해봤습니다. (옆동네에서 사용하고 있길래 보니까 괜찮은 것 같아요!)
사실 장점들이 지금 프로젝트에서는 필요 없긴 한데 궁금해서 써봤습니다 :)
9d402e8

2021-10-31 07:43 UTC, laco-dev approved these changes
LGTM 🐈 👍 🐕

2021-11-01 14:20 UTC, merged