스플래쉬 & 로그인 화면 이동 정의
DDD-Community/appcha-android pull request #33
Opened 2021-11-05 14:23 UTC by peterchoee

**작업내용**
- 스플래쉬 화면에서 Preferences(Local) 유무에 따라 로그인 화면 혹은 메인 화면으로 이동할 수 있도록 구현
- 로그인 화면에서 카카오 토큰을 가지고 UseCase를 호출하도록 구현 (Remote 구현 필요)
- gRPC 헤더 내에 Preferneces를 참조해 Token을 가져오도록 구현

_로그인 관련 gRPC 구현에 대해서 추가 커밋 예정_

2021-11-05 14:33 UTC, laco-dev requested changes
프로필에 토큰을 포함시키지 말아주세요. 필요하면 유저를 다시 가져오면 됩니다
로그인은 로그인만 해서 토큰값을 저장하는 비즈니스 로직을 수행하게 해주세요.

User에 이미 프로필 클래스가 있습니다
- https://github.com/DDD-6/appcha-protobuf/blob/main/protobuf/service/user_service.proto

2021-11-06 09:02 UTC, peterchoee commented
> 프로필에 토큰을 포함시키지 말아주세요. 필요하면 유저를 다시 가져오면 됩니다 로그인은 로그인만 해서 토큰값을 저장하는 비즈니스 로직을 수행하게 해주세요. https://github.com/DDD-6/appcha-protobuf/blob/main/protobuf/service/user_service.proto User에 이미 프로필 클래스가 있습니다

리뷰주신 부분이랑 미흡한 부분 내일까지 완료할게요!
리뷰 감사합니다 :)

2021-11-07 17:36 UTC, peterchoee commented
> 프로필에 토큰을 포함시키지 말아주세요. 필요하면 유저를 다시 가져오면 됩니다 로그인은 로그인만 해서 토큰값을 저장하는 비즈니스 로직을 수행하게 해주세요. https://github.com/DDD-6/appcha-protobuf/blob/main/protobuf/service/user_service.proto User에 이미 프로필 클래스가 있습니다

리뷰내용 반영했습니다. 2311633
data 레이어에서 loginKakao 로직 처리할때 에러처리는 추후에 gRPC 연동하면서 조금 더 볼게요.

2021-11-08 01:20 UTC, laco-dev commented on modules/data/src/main/java/com/editor/appcha/data/source/TokenLocalDataSource.kt
> +    suspend fun getToken() : Result<Boolean>
getToken이 Boolean을 반환하는 형태는 맞지 않는 것 같습니다.

2021-11-08 01:24 UTC, laco-dev commented on modules/local/src/main/java/com/editor/appcha/local/TokenLocalDataSourceImpl.kt
> +    }
buildRestulCatching { ... } 형태로 사용하시면 됩니다

2021-11-08 01:24 UTC, laco-dev commented on modules/domain/src/main/java/com/editor/appcha/domain/model/Profile.kt
> +) : DomainModel
Profile을 따로 만드신거면 User에 선언된 Profile 정보도 옮겨 주세요

2021-11-08 01:24 UTC, laco-dev commented on modules/ui/src/main/java/com/editor/appcha/ui/theme/Color.kt
> +val kakaoTitle = Color(0xFF191919)
Color는 상수 값으로 사용되서 UpperCamelCase로 작성 해주시면 됩니다

2021-11-08 01:24 UTC, laco-dev commented on modules/ui/src/main/java/com/editor/appcha/ui/theme/Dimens.kt
> +val buttonKakao = 45.dp
Kakao 버튼이 컴포넌트로 사용되면 Composable을 파일로 분리하고 해당 파일에서 private val로 가지고 있도록 하면 됩니다

2021-11-08 04:48 UTC, peterchoee commented on modules/ui/src/main/java/com/editor/appcha/ui/theme/Dimens.kt
> +val buttonKakao = 45.dp
별도로 궁금한 내용이 있는데요.
일반적으로 컴포즈에서 리소스 파일을 분리하고자할때 Dimens.xml 에 대해서는 위와 같이 Color, Shape 등 파일로 관리되는 것처럼 정의하는게 적절한 방식이 맞나요~?

2021-11-08 08:38 UTC, peterchoee commented on modules/ui/src/main/java/com/editor/appcha/ui/theme/Dimens.kt
> +val buttonKakao = 45.dp
리뷰내용 확인부탁드려요 :)
8fdd19d

2021-11-12 12:40 UTC, laco-dev commented on modules/ui/src/main/java/com/editor/appcha/ui/theme/Dimens.kt
> +val buttonKakao = 45.dp
기존 안드로이드 리소스 시스템의 장점은 그대로 사용할 수 있어서 dimens.xml를 사용하기도 합니다.

Kotlin 코드로만 분기에 따라 다르게 적용하는 샘플
https://proandroiddev.com/supporting-different-screen-sizes-on-android-with-jetpack-compose-f215c13081bd

2021-11-12 12:41 UTC, laco-dev approved these changes
수고하셨습니다
진행을 위해 머지 부탁드립니다.

2021-11-13 07:08 UTC, merged