Kotlin DSL 적용
DDD-Community/appcha-android pull request #8
Opened 2021-09-03 15:42 UTC by peterchoee

**작업내용**
- .gitignore 추가
- buildSrc 추가 & Config, Dependency 등 의존성 관련 상수 정의
- 기존 Groovy Gradle에서 Kotlin 스크립트로 수정

2021-09-04 09:52 UTC, laco-dev requested changes

2021-09-04 09:52 UTC, laco-dev commented on build.gradle.kts
> +        classpath(Configs.Project.HILT)
이것도 Dependencies로 선언될 수 있는 애들이라 (플러그인 개발 등) Dependencies 로 옮겨서 만들어 주세요.

buildSrc같은데서 플러그인을 개발하거나 gradle 관련 코드를 작성할때 의존성에 넣고는 합니다.

2021-09-04 09:52 UTC, laco-dev commented on buildSrc/src/main/kotlin/Configs.kt
> +    const val LIBRARY                   = "com.android.library"
java-library
kotlin-library와 같이 라이브러리가 여러 종류가 될 수 있습니다

2021-09-04 09:52 UTC, laco-dev commented on buildSrc/src/main/kotlin/Configs.kt
> +    const val HILT                      = "dagger.hilt.android.plugin"
플러그인 관련 스펙은 
buildSrc에서 스쿱을 제한해서 보다 안전하고 직관적으로 선언이 가능한 방식이 있습니다.

```kotlin
inline val PluginDependenciesSpec.`android-library` get() = id("com.android.library")

plugins { 
    `android-library`
    ...
}
```

`maven-publish` 같은 확장 프로퍼티가 이런식으로 사용합니다

2021-09-04 09:52 UTC, laco-dev commented on buildSrc/src/main/kotlin/Versions.kt
> +    const val COMPOSE_NAVIGATION    = "2.4.0-alpha08"
네비게이션은 컴포즈에서 별도의 artifact으로 분리되어 있지 않은데 나눌 필요가 있을까요?

2021-09-04 09:52 UTC, laco-dev commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val COROUTINES                = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.COROUTINES}"
`COROUTINES_ANDROID`도  추가 해주세요

2021-09-04 09:52 UTC, laco-dev commented on modules/domain/build.gradle.kts
> +}
```kotlin
plugins {
    kotlin("jvm")
    kotlin("android")
    kotlin('kapt")
}
```
형태로 작성 해주세요 사전에 제공하는 플러그인 확장 함수입니다

2021-09-04 09:52 UTC, laco-dev commented on modules/local/build.gradle.kts
> +    kapt(Dependencies.ROOM_COMPILER)
룸이 지금 필요할까요?

2021-09-04 09:52 UTC, laco-dev commented on modules/presentation/build.gradle.kts
> +    implementation(Dependencies.COROUTINES)
ui 모듈에서는 `coroutines-android`로 사용 해 주세요

2021-09-04 09:52 UTC, laco-dev commented on buildSrc/src/main/kotlin/Versions.kt
> +    const val COROUTINES            = "1.3.9"
코루틴 현재 Stable 버전은 `1.5.2` 입니다.
혹시 `1.3.9`로 사용해야 하는 다른 이유가 있을까요?

2021-09-04 09:52 UTC, laco-dev commented on modules/presentation/build.gradle.kts
> +    implementation(Dependencies.COROUTINES)
```kotlin
androidx.compose.ui:ui:1.0.1
|    +--- androidx.compose.runtime:runtime-saveable:1.0.1
|    |    +--- androidx.compose.runtime:runtime:1.0.1
|    |    |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.0 (*)
|    |    |    +--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.5.21 (*)
|    |    +--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.5.21 (*)
```

Dependencies 그래프 상으로 coroutines-android를 의존성을 전이성으로 가져오고 있습니다.
하위버전은 무시 됩니다

안드로이드 우측 gradle 탭에서 의존성 목록을 리스트 형태로 확인 가능합니다

2021-09-04 09:52 UTC, laco-dev commented on modules/presentation/proguard-rules.pro
> +# proguardFiles setting in build.gradle.kts.kts.kts.kts.kts.
???

2021-09-05 11:13 UTC, peterchoee commented on buildSrc/src/main/kotlin/Configs.kt
> +    const val LIBRARY                   = "com.android.library"
혹시 domain 모듈에서 쓰일까요~?
DSL 작업 기준 java-library를 쓰는 모듈이 없어서 추가는 안했었어요!

2021-09-05 11:14 UTC, peterchoee commented on modules/domain/build.gradle.kts
> +}
요거는 id() 로 통일해서 작성하려한건데요.
다른 코멘트에서 말씀주신 PluginDependenciesSpec 활용해서 진행하도록 할게요!

2021-09-05 11:14 UTC, peterchoee commented on modules/local/build.gradle.kts
> +    kapt(Dependencies.ROOM_COMPILER)
음.. 필요없을 것 같네요! 추후에 필요하면 넣으시죠 ㅎ

2021-09-05 11:20 UTC, peterchoee commented on buildSrc/src/main/kotlin/Versions.kt
> +    const val COMPOSE_NAVIGATION    = "2.4.0-alpha08"
artifact 분리는 없는데 기존 stable 버전에서 navigation-compose를 별도로 지원하는지 모르겠어서 버전은 분리해놨었어요!
우선 navigation-compose 제거하고 추후 피처 개발 시에 필요하면 다시 살펴보고 넣도록할게요~

2021-09-05 11:20 UTC, peterchoee commented
전체적으로 놓친 부분이 많은데 꼼꼼하게 봐주셔서 감사합니다 :)
잘 몰랐던 새로운 부분도 있어서 좋네요~

2021-09-05 12:45 UTC, laco-dev approved these changes
LGTM 🐈 🐕

2021-09-05 13:13 UTC, merged